# Generated by Django 6.0.5 on 2026-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='centers',
            field=models.ManyToManyField(blank=True, to='centers.center'),
        ),
    ]
