# Generated by Django 6.0.5 on 2026-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_centers'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='centers.center'),
        ),
    ]
